const PDFDocument = require('pdfkit');

const generateReport = (data) => {
    const doc = new PDFDocument({ margin: 50 });

    // --- Header ---
    doc
        .fillColor('#444444')
        .fontSize(20)
        .text('Security & Privacy Report', { align: 'center' })
        .moveDown(0.5);

    doc
        .fontSize(10)
        .text('Generated by LaunchPad Code', { align: 'center' })
        .text(`Date: ${new Date().toLocaleDateString()}`, { align: 'center' })
        .moveDown();

    doc
        .strokeColor("#aaaaaa")
        .lineWidth(1)
        .moveTo(50, doc.y)
        .lineTo(550, doc.y)
        .stroke()
        .moveDown();

    // --- User Profile ---
    const user = data.user;
    doc
        .fillColor('#000000')
        .fontSize(16)
        .text('User Profile', { underline: true })
        .moveDown(0.5)
        .fontSize(12)
        .text(`Name: ${user.name}`)
        .text(`Email: ${user.email}`)
        .text(`Account Status: Active`)
        .moveDown();

    // --- Security Scorecard ---
    // Basic Logic for Score if not present
    // Base 70, +20 for 2FA, -15 per breach
    const subs = data.subscriptions || [];
    const breaches = subs.filter((s) => s.breachStatus?.isBreached);

    let score = user.securityScore;
    if (score === undefined || score === null) {
        score = 70;
        if (user.is2FAEnabled) score += 20;
        score -= (breaches.length * 15);
        if (score < 0) score = 0;
        if (score > 100) score = 100;
    }

    let scoreColor = '#cc0000'; // Red
    if (score > 50) scoreColor = '#e6b800'; // Yellow
    if (score > 80) scoreColor = '#008800'; // Green

    doc
        .fontSize(16)
        .text('Security Scorecard', { underline: true })
        .moveDown(0.5);

    doc
        .fontSize(14)
        .fillColor(scoreColor)
        .text(`Security Score: ${score}/100`)
        .fillColor('#000000'); // Reset

    doc
        .fontSize(12)
        .text(`Two-Factor Authentication: ${user.is2FAEnabled ? 'Enabled ✅' : 'Disabled ❌'}`)
        .moveDown();

    // --- Subscription Analysis ---
    const activeSubs = subs.filter((s) => s.status === 'active');
    const monthlyCost = subs.reduce((acc, s) => {
        if (s.financials?.currency === 'USD') {
            if (s.financials.period === 'monthly') return acc + s.financials.cost;
            if (s.financials.period === 'yearly') return acc + s.financials.cost / 12;
        }
        return acc;
    }, 0);

    doc
        .fontSize(16)
        .text('Subscription Analysis', { underline: true })
        .moveDown(0.5)
        .fontSize(12)
        .text(`Total Subscriptions Found: ${subs.length}`)
        .text(`Active Subscriptions: ${activeSubs.length}`)
        .text(
            `Estimated Monthly Spend: $${monthlyCost.toFixed(2)}`
        )
        .moveDown();

    // --- Breach Report ---
    doc
        .fontSize(16)
        .fillColor(breaches.length > 0 ? '#cc0000' : '#000000')
        .text('Breach Monitoring', { underline: true })
        .moveDown(0.5);

    if (breaches.length === 0) {
        doc
            .fontSize(12)
            .fillColor('#008800')
            .text('✅ No active breaches detected in your linked accounts.');
    } else {
        doc
            .fontSize(12)
            .fillColor('#cc0000')
            .text(`⚠️ Warning: ${breaches.length} compromised accounts found.`);

        doc.moveDown(0.5);

        breaches.forEach((b) => {
            doc
                .fillColor('#000000')
                .fontSize(10)
                .text(
                    `• ${b.serviceName} (${b.domain}): ${b.breachStatus.breachName}`
                )
                .text(
                    `  Severity: ${b.breachStatus.severity?.toUpperCase()} | Date: ${b.breachStatus.breachDate ? new Date(b.breachStatus.breachDate).toLocaleDateString() : 'Unknown'}`
                    , { indent: 10 })
                .moveDown(0.3);
        });
    }

    doc.moveDown();

    // --- Recommendations ---
    doc
        .fontSize(16)
        .fillColor('#000000')
        .text('Recommendations', { underline: true })
        .moveDown(0.5)
        .fontSize(12);

    if (!user.is2FAEnabled) {
        doc.text('• [CRITICAL] Enable Two-Factor Authentication (2FA) immediately.');
    }
    if (breaches.length > 0) {
        doc.text('• [CRITICAL] Change passwords for compromised services.');
    }
    if (score < 50) {
        doc.text('• Review your email sharing habits.');
    }
    doc.text('• Regularly revoke access to unused services.');

    // --- Footer ---
    const bottom = doc.page.height - 50;
    doc
        .fontSize(8)
        .fillColor('grey')
        .text(
            'Disclaimer: This report is generated based on automated email analysis. It may not cover all security vectors.',
            50,
            bottom,
            { align: 'center', width: 500 }
        );

    doc.end();
    return doc;
};

module.exports = { generateReport };
